### ISSUE TITLE
LICENSE file is missing.

### ISSUE THREAD

**Issue by Djelibeybi** [frozen2077/lifx_joy#1]
Hey, thanks for sharing your modifications! 

As your code is a derivative work of two other repos, please would you add an appropriate Apache-2.0 `LICENSE` file in the root folder and an MIT `LICENSE` file in `aiolifx2` as the two upstream projects have different licenses and it would be good to identify you code is under the same license as each of its upstream sources.

You can copy the appropriate file from each of the two upstream projects and add your copyright to each as well.

**Comment by Djelibeybi** [comment]
I wanted to see what your changes were, so I created a repo that has the upstream code as the intial commit and then your code as subsequent commits: https://github.com/Djelibeybi/lifx_joy

A side-effect of this is that it has the upstream license files. :)

**Comment by frozen2077** [comment]
> I wanted to see what your changes were, so I created a repo that has the upstream code as the intial commit and then your code as subsequent commits: https://github.com/Djelibeybi/lifx_joy
> 
> A side-effect of this is that it has the upstream license files. :)

Sorry for the late replay, was debugging a weird problem yesterday, turns out aiolifx would generate an extra 00 byte in the build set64 msg function.
Also updated the license file and readme this time :)
